In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


In [2]:
data = pd.read_csv("IMDB Dataset.csv")
data

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
# Review Example
data['review'][2]

'I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.<br /><br />This was the most I\'d laughed at one of Woody\'s comedies in years (dare I say a decade?). While I\'ve never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.'

In [5]:
data.shape

(50000, 2)

In [6]:
data['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB


In [8]:
#! pip install nltk

# Text Preprocessing
* Steps
1) Encoding target column if textual
2) Remove HTML tags
3) Remove Special characters
4) Converting everything to lower case
5) Removing stop words
6) Stemming

# Encoding

In [9]:
data['sentiment'].replace({'positive' : 1, 'negative' : 0}, inplace= True)

In [10]:
data.head()

review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

# Remove HTML tags

In [11]:
# Example
clean = re.compile('<.*?>')
re.sub(clean, '', data.iloc[2].review)

'I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.This was the most I\'d laughed at one of Woody\'s comedies in years (dare I say a decade?). While I\'ve never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.'

In [12]:
# Main operation
def clear_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

data['review'] = data['review'].apply(clear_html)

# Remove special characters

In [13]:
def remove_special(text):
    x = ''
    
    for i in text:
        if i.isalnum():
            x = x + i
        else:
            x = x + ' '
    return x

In [14]:
# Example
remove_special('I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.This was the most I\'d laughed at one of Woody\'s comedies in years (dare I say a decade?). While I\'ve never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.')

'I thought this was a wonderful way to spend time on a too hot summer weekend  sitting in the air conditioned theater and watching a light hearted comedy  The plot is simplistic  but the dialogue is witty and the characters are likable  even the well bread suspected serial killer   While some may be disappointed when they realize this is not Match Point 2  Risk Addiction  I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love This was the most I d laughed at one of Woody s comedies in years  dare I say a decade    While I ve never been impressed with Scarlet Johanson  in this she managed to tone down her  sexy  image and jumped right into a average  but spirited young woman This may not be the crown jewel of his career  but it was wittier than  Devil Wears Prada  and more interesting than  Superman  a great comedy to go see with friends '

In [15]:
# Main operation
data['review'] = data['review'].apply(remove_special)

# Converting everything to lower case

In [16]:
def convert_lower(text):
    return text.lower()

data['review'] = data['review'].apply(convert_lower)

In [17]:
# Output
data['review'][2]

'i thought this was a wonderful way to spend time on a too hot summer weekend  sitting in the air conditioned theater and watching a light hearted comedy  the plot is simplistic  but the dialogue is witty and the characters are likable  even the well bread suspected serial killer   while some may be disappointed when they realize this is not match point 2  risk addiction  i thought it was proof that woody allen is still fully in control of the style many of us have grown to love this was the most i d laughed at one of woody s comedies in years  dare i say a decade    while i ve never been impressed with scarlet johanson  in this she managed to tone down her  sexy  image and jumped right into a average  but spirited young woman this may not be the crown jewel of his career  but it was wittier than  devil wears prada  and more interesting than  superman  a great comedy to go see with friends '

# Removing stop words

In [18]:
stopwords_list = stopwords.words('english')
print(stopwords_list)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [19]:
def remove_stopwords(text):
    x = []
    for i in text.split():
        if i not in stopwords.words('english'):
            x.append(i)
    y = x[:]
    x.clear()
    return y

data['review'] = data['review'].apply(remove_stopwords)

In [20]:
data.head()

review  sentiment
0  [one, reviewers, mentioned, watching, 1, oz, e...          1
1  [wonderful, little, production, filming, techn...          1
2  [thought, wonderful, way, spend, time, hot, su...          1
3  [basically, family, little, boy, jake, thinks,...          0
4  [petter, mattei, love, time, money, visually, ...          1

# Stemming

In [21]:
ps = PorterStemmer()

y = []

def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z = y[:]
    y.clear()
    return z

data['review'] = data['review'].apply(stem_words)

# List to String

In [22]:
def list_to_string(text):
    return ' '.join(text)

data['review'] = data['review'].apply(list_to_string)

In [23]:
data['review'][0]

'one review mention watch 1 oz episod hook right exactli happen first thing struck oz brutal unflinch scene violenc set right word go trust show faint heart timid show pull punch regard drug sex violenc hardcor classic use word call oz nicknam given oswald maximum secur state penitentari focus mainli emerald citi experiment section prison cell glass front face inward privaci high agenda em citi home mani aryan muslim gangsta latino christian italian irish scuffl death stare dodgi deal shadi agreement never far away would say main appeal show due fact goe show dare forget pretti pictur paint mainstream audienc forget charm forget romanc oz mess around first episod ever saw struck nasti surreal say readi watch develop tast oz got accustom high level graphic violenc violenc injustic crook guard sold nickel inmat kill order get away well manner middl class inmat turn prison bitch due lack street skill prison experi watch oz may becom comfort uncomfort view that get touch darker side'

# Vectorization

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

In [31]:
cv = CountVectorizer(max_features=5000)
#cv = CountVectorizer()
X = cv.fit_transform(data['review']).toarray()

In [32]:
X.shape

(50000, 5000)

In [33]:
y = data.iloc[:,-1].values

In [34]:
y.shape

(50000,)

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [36]:
X_train.shape, y_train.shape

((40000, 5000), (40000,))

In [37]:
X_test.shape, y_test.shape

((10000, 5000), (10000,))

In [38]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [39]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

In [40]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)
clf3.fit(X_train, y_train)

BernoulliNB()

In [41]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)
y_pred3 = clf3.predict(X_test)

In [46]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print('GaussianNB:')
print('Accuracy Score:', accuracy_score(y_test,y_pred1))
print('Confusion Matrix:\n', confusion_matrix(y_test,y_pred1))
print('Classification Report:\n', classification_report(y_test,y_pred1))

GaussianNB:
Accuracy Score: 0.7156
Confusion Matrix:
 [[4324  663]
 [2181 2832]]
Classification Report:
               precision    recall  f1-score   support

           0       0.66      0.87      0.75      4987
           1       0.81      0.56      0.67      5013

    accuracy                           0.72     10000
   macro avg       0.74      0.72      0.71     10000
weighted avg       0.74      0.72      0.71     10000



In [47]:
print('MultinomialNB:')
print('Accuracy Score: ',accuracy_score(y_test,y_pred2))
print('Confusion Matrix:\n ',confusion_matrix(y_test,y_pred2))
print('Classification Report:\n ',classification_report(y_test,y_pred2))

MultinomialNB:
Accuracy Score:  0.8517
Confusion Matrix:
  [[4285  702]
 [ 781 4232]]
Classification Report:
                precision    recall  f1-score   support

           0       0.85      0.86      0.85      4987
           1       0.86      0.84      0.85      5013

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000



In [48]:
print('BernoulliNB:')
print('Accuracy Score: ',accuracy_score(y_test,y_pred3))
print('Confusion Matrix:\n ',confusion_matrix(y_test,y_pred3))
print('Classification Report:\n ',classification_report(y_test,y_pred3))

BernoulliNB:
Accuracy Score:  0.8497
Confusion Matrix:
  [[4305  682]
 [ 821 4192]]
Classification Report:
                precision    recall  f1-score   support

           0       0.84      0.86      0.85      4987
           1       0.86      0.84      0.85      5013

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000



In [49]:
from sklearn.tree import DecisionTreeClassifier

In [50]:
dt = DecisionTreeClassifier()

In [51]:
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [54]:
pred = dt.predict(X_test)
pred

array([0, 1, 1, ..., 1, 0, 0], dtype=int64)

In [55]:
pred = pd.DataFrame(pred)

In [56]:
print('Accuracy Score: ',accuracy_score(y_test,pred))
print('Confusion Matrix:\n ',confusion_matrix(y_test,pred))
print('Classification Report:\n ',classification_report(y_test,pred))

Accuracy Score:  0.7208
Confusion Matrix:
  [[3577 1410]
 [1382 3631]]
Classification Report:
                precision    recall  f1-score   support

           0       0.72      0.72      0.72      4987
           1       0.72      0.72      0.72      5013

    accuracy                           0.72     10000
   macro avg       0.72      0.72      0.72     10000
weighted avg       0.72      0.72      0.72     10000

